[global]
debug = false

[gunicorn]
bind = "0.0.0.0:8080"
workers = 2
timeout = 30
worker_class = "uvicorn.workers.UvicornWorker"

[database]
host = "localhost"
port = "5432"
name = "race_simulation"
user = "postgres"
password = "postgres"

[redis]
host = "localhost"
port = 6379