repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.7
    hooks:
      - id: ruff
        args: [
          --fix,
          --show-fixes,
          --config=backend/pyproject.toml
        ]
      - id: ruff-format
        args: [--line-length=89]
