"""empty message

Revision ID: 45c026c5a1f6
Revises: 
Create Date: 2025-04-05 04:50:58.577798

"""
from decimal import Decimal
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c026c5a1f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colour', sa.String(length=20), nullable=False),
    sa.Column('reaction_time', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('acceleration', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('max_speed', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('speed_decay', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race_result',
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('finish_time', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('race_id', 'student_id')
    )
    students_data = [
        {
            'colour': 'красный',
            'reaction_time': Decimal('0.12'),
            'acceleration': Decimal('3.80'),
            'max_speed': Decimal('9.85'),
            'speed_decay': Decimal('0.085')
        },
        {
            'colour': 'синий',
            'reaction_time': Decimal('0.18'),
            'acceleration': Decimal('4.20'),
            'max_speed': Decimal('10.10'),
            'speed_decay': Decimal('0.120')
        },
        {
            'colour': 'желтый',
            'reaction_time': Decimal('0.25'),
            'acceleration': Decimal('3.50'),
            'max_speed': Decimal('9.45'),
            'speed_decay': Decimal('0.150')
        },
        {
            'colour': 'зеленый',
            'reaction_time': Decimal('0.15'),
            'acceleration': Decimal('3.95'),
            'max_speed': Decimal('10.25'),
            'speed_decay': Decimal('0.095')
        },
        {
            'colour': 'фиолетовый',
            'reaction_time': Decimal('0.22'),
            'acceleration': Decimal('4.05'),
            'max_speed': Decimal('9.65'),
            'speed_decay': Decimal('0.110')
        },
        {
            'colour': 'черный',
            'reaction_time': Decimal('0.10'),
            'acceleration': Decimal('4.50'),
            'max_speed': Decimal('10.50'),
            'speed_decay': Decimal('0.050')
        }
    ]

    op.bulk_insert(
        sa.table('student',
            sa.Column('colour', sa.String),
            sa.Column('reaction_time', sa.Numeric),
            sa.Column('acceleration', sa.Numeric),
            sa.Column('max_speed', sa.Numeric),
            sa.Column('speed_decay', sa.Numeric)
        ),
        students_data
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('race_result')
    op.drop_table('student')
    op.drop_table('race')
    # ### end Alembic commands ###
